setwd("C:/Users/TompkinsD/Documents/coursera2019/r4")

power <- read.csv("C:/Users/TompkinsD/Documents/coursera2019/r4/household_power_consumption.txt", sep=";", na.strings=c("?"))
power$DateTime <- paste(power$Date,power$Time)
power$DateTime <- strptime(power$DateTime, "%d/%m/%Y %H:%M:%S")
power$Date <- as.Date(power$Date, "%d/%m/%Y")
power <- subset(power, "2007-02-01" <= Date & "2007-02-02" >= Date)

png(file="plot4.png")
par(mfrow=c(2,2))
with(power, plot(DateTime, Global_active_power, pch=NA,xlab=" ",ylab="Global Active Power (Killowats)"))
lines(power$DateTime, power$Global_active_power)
with(power, plot(DateTime, Voltage, pch=NA))
lines(power$DateTime, power$Voltage)
with(power, plot(DateTime, Sub_metering_1, pch=NA, xlab=" ", ylab = "Energy sub metering"))
lines(power$DateTime, power$Sub_metering_1)
lines(power$DateTime, power$Sub_metering_2, col="red")
lines(power$DateTime, power$Sub_metering_3, col="blue")
legend("topright", lty=1, col=c("black","red","blue"), legend = c("sub_metering_1","sub_metering_2","sub_metering_3"))
with(power, plot(DateTime, Global_reactive_power, pch=NA))
lines(power$DateTime, power$Global_reactive_power)
dev.off()